/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path');

const { platform, arch } = process;

let nativeBinding = null;
let localFileExisted = false;
let loadError = null;

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim();
      return readFileSync(lddPath, 'utf8').includes('musl');
    } catch (e) {
      return true;
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header;
    return !glibcVersionRuntime;
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'currant.android-arm64.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./currant.android-arm64.node');
          } else {
            nativeBinding = require('currant-android-arm64');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'currant.android-arm-eabi.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./currant.android-arm-eabi.node');
          } else {
            nativeBinding = require('currant-android-arm-eabi');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`);
    }
    break;
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'currant.win32-x64-msvc.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./currant.win32-x64-msvc.node');
          } else {
            nativeBinding = require('currant-win32-x64-msvc');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case 'ia32':
        localFileExisted = existsSync(join(__dirname, 'currant.win32-ia32-msvc.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./currant.win32-ia32-msvc.node');
          } else {
            nativeBinding = require('currant-win32-ia32-msvc');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'currant.win32-arm64-msvc.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./currant.win32-arm64-msvc.node');
          } else {
            nativeBinding = require('currant-win32-arm64-msvc');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`);
    }
    break;
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'currant.darwin-universal.node'));
    try {
      if (localFileExisted) {
        nativeBinding = require('./currant.darwin-universal.node');
      } else {
        nativeBinding = require('currant-darwin-universal');
      }
      break;
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'currant.darwin-x64.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./currant.darwin-x64.node');
          } else {
            nativeBinding = require('currant-darwin-x64');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'currant.darwin-arm64.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./currant.darwin-arm64.node');
          } else {
            nativeBinding = require('currant-darwin-arm64');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`);
    }
    break;
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`);
    }
    localFileExisted = existsSync(join(__dirname, 'currant.freebsd-x64.node'));
    try {
      if (localFileExisted) {
        nativeBinding = require('./currant.freebsd-x64.node');
      } else {
        nativeBinding = require('currant-freebsd-x64');
      }
    } catch (e) {
      loadError = e;
    }
    break;
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'currant.linux-x64-musl.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./currant.linux-x64-musl.node');
            } else {
              nativeBinding = require('currant-linux-x64-musl');
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'currant.linux-x64-gnu.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./currant.linux-x64-gnu.node');
            } else {
              nativeBinding = require('currant-linux-x64-gnu');
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'currant.linux-arm64-musl.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./currant.linux-arm64-musl.node');
            } else {
              nativeBinding = require('currant-linux-arm64-musl');
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'currant.linux-arm64-gnu.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./currant.linux-arm64-gnu.node');
            } else {
              nativeBinding = require('currant-linux-arm64-gnu');
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'currant.linux-arm-musleabihf.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./currant.linux-arm-musleabihf.node');
            } else {
              nativeBinding = require('currant-linux-arm-musleabihf');
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'currant.linux-arm-gnueabihf.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./currant.linux-arm-gnueabihf.node');
            } else {
              nativeBinding = require('currant-linux-arm-gnueabihf');
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'currant.linux-riscv64-musl.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./currant.linux-riscv64-musl.node');
            } else {
              nativeBinding = require('currant-linux-riscv64-musl');
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'currant.linux-riscv64-gnu.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./currant.linux-riscv64-gnu.node');
            } else {
              nativeBinding = require('currant-linux-riscv64-gnu');
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case 's390x':
        localFileExisted = existsSync(join(__dirname, 'currant.linux-s390x-gnu.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./currant.linux-s390x-gnu.node');
          } else {
            nativeBinding = require('currant-linux-s390x-gnu');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`);
    }
    break;
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`);
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError;
  }
  throw new Error(`Failed to load native binding`);
}

const {
  createExecution,
  claimExecution,
  completeExecution,
  failExecution,
  suspendWorkflow,
  resumeWorkflow,
  getExecution,
  getWorkflowActivities,
  updateHeartbeat,
  stopWorker,
  recoverDeadWorkers,
  sendSignal,
  getSignals,
  consumeSignal,
  migrate,
} = nativeBinding;

module.exports.createExecution = createExecution;
module.exports.claimExecution = claimExecution;
module.exports.completeExecution = completeExecution;
module.exports.failExecution = failExecution;
module.exports.suspendWorkflow = suspendWorkflow;
module.exports.resumeWorkflow = resumeWorkflow;
module.exports.getExecution = getExecution;
module.exports.getWorkflowActivities = getWorkflowActivities;
module.exports.updateHeartbeat = updateHeartbeat;
module.exports.stopWorker = stopWorker;
module.exports.recoverDeadWorkers = recoverDeadWorkers;
module.exports.sendSignal = sendSignal;
module.exports.getSignals = getSignals;
module.exports.consumeSignal = consumeSignal;
module.exports.migrate = migrate;
